### ISSUE TITLE
Running locally does not work

### ISSUE THREAD

**Issue by reverbePrintemps** [Gapur/firebase-push-notifications#1]
After following your intstructions to run this locally, I am faced with the following error: `Uncaught FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).`

May I suggest you publish this project as a GitHub Pages site? This way folks can check it out live vs having to run it locally. :)

**Comment by Gapur** [comment]
Hey, it looks like you forgot to add `projectId` to `.env` file. Could you check?

**Comment by reverbePrintemps** [comment]
Oh my, I'd added colons instead of equal signs in the .env file. *facepalm* My apologies! I'll close this issue now. :)
